[tool.poetry]
name = "georges-core"
version = "0.1.0"
description = ""
authors = ["Cédric Hernalsteens <cedric.hernalsteens@ulb.be>"]

[tool.poetry.dependencies]
python = ">3.8.1 <3.10"
boost-histogram = "^1.0.2"
matplotlib = "^3.4.2"
numpy = "^1.20.3"
Pint = "^0.17"
uproot = "^4.0.8"
vtk = "^9.0.1"
plotly = "^4.14.3"
pandas = "^1.2.4"
numpy-quaternion = "^2021.4.5"
numba = "^0.53.1"
scipy = "^1.6.3"
PyYAML = "^5.4.1"
mergedeep = "^1.3.4"
pybdsim = { git = "https://bitbucket.org/jairhul/pybdsim.git", branch = "dev_failsim" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
