[tool.poetry]
name = "georges-core"
version = "2022.1"
description = ""
authors = ["Cédric Hernalsteens <cedric.hernalsteens@ulb.be>",
           "Robin Tesse <robin.tesse@ulb.be>",
           "Eustache Gnacadja <eustache.gnacadja@ulb.be>",
           "Eliott Ramoisiaux <eliott.ramoisiaux@ulb.be>",
           "Marion Vanwelde <marion.vanwelde@ulb.be>"]


[tool.poetry.dependencies]
python = ">3.8.1 <3.11"
boost-histogram = "^1.3.2"
matplotlib = "^3.6.2"
numpy = "^1.23.4"
Pint = "^0.17"
uproot = "^4.3.7"
vtk = "^9.2.2"
plotly = "^5.11.0"
pandas = "^1.5.1"
numpy-quaternion = "^2022.4.2"
numba = "^0.56.4"
scipy = "^1.9.3"
PyYAML = "^5.4.1"
mergedeep = "^1.3.4"
awkward = "^1.10.2"
pyarrow = "^10.0.0"
fastparquet = "^2022.11.0"
cpymad = "^1.10.0"
pytest-cov = "^4.0.0"

pybdsim = { git = "https://bitbucket.org/jairhul/pybdsim", branch = "feature_uproot" }

sphinx = { version = "^5.3.0", optional = true }
sphinx-material = { version = "^0.0.35", optional = true }
sphinx-automodapi = { version = "^0.14.1", optional = true }
sphinxcontrib-bibtex = { version = "^2.2.0", optional = true }
sphinx-copybutton = { version = "^0.5.1", optional = true }
sphinx-autobuild = { version = "^2021.3.14", optional = true }
sphinx-rtd-theme = {version = "^1.1.1", optional = true}
m2r2 = { version = "^0.2.8", optional = true }
pandoc = { version = "^1.0.2", optional = true }
nbsphinx = { version = "^0.8.2", optional = true }
ipython = { version = "^8.6.0", optional = true }
pytest = { version = "^7.2.0", optional = true }
pytest-bdd = { version = "^6.1.1", optional = true }
ipykernel = "^6.17.1"
cpymad = "^1.9.3"


[tool.poetry.dev-dependencies]
yapf = "^0.32.0"
flake8 = "^5.0.4"
tox = "^3.27.1"
tox-poetry-installer = "^0.10.0"

[tool.poetry.extras]
sphinx = [
    "sphinx",
    "sphinx-material",
    "sphinx-automodapi",
    "sphinxcontrib-bibtex",
    "sphinx-copybutton",
    "sphinx-autobuild",
    "sphinx-rtd-theme",
    "sphinx_book_theme",
    "m2r2",
    "pandoc",
    "nbsphinx",
    "ipython",
]

test = [
    "pytest",
    "pytest-bdd",
    "tox",
    "tox-poetry-installer"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
